environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
os: Visual Studio 2017 # Windows Server 2016
install:
  - java -version
  - gradlew.bat --version
# The 'build' task runs most things, including test, check, & static analysis
build: off
test_script: gradlew.bat -u -i -S build
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
